---
apiVersion: crunchydata.com/v1
kind: Pgcluster
metadata:
  annotations:
    current-primary: my-sample-db
  labels:
    crunchy-pgha-scope: my-sample-db
    deployment-name: my-sample-db
    name: my-sample-db
    pg-cluster: my-sample-db
    pgo-version: 4.7.0
    pgouser: admin
  name: my-sample-db
  namespace: pgo
spec:
  BackrestStorage:
    accessmode: ReadWriteOnce
    matchLabels: ""
    name: ""
    size: 5Gi
    storageclass: "local-path"
    storagetype: dynamic
    supplementalgroups: ""
  PrimaryStorage:
    accessmode: ReadWriteOnce
    matchLabels: ""
    name: my-sample-db
    size: 5Gi
    storageclass: "local-path"
    storagetype: dynamic
    supplementalgroups: ""
  ReplicaStorage:
    accessmode: ReadWriteOnce
    matchLabels: ""
    name: ""
    size: 5Gi
    storageclass: "local-path"
    storagetype: dynamic
    supplementalgroups: ""
  annotations: {}
  ccpimage: crunchy-postgres-ha
  ccpimageprefix: registry.developers.crunchydata.com/crunchydata
  ccpimagetag: centos8-13.3-4.7.0
  clustername: my-sample-db
  database: my-sample-db
  exporterport: "9187"
  limits: {}
  name: my-sample-db
  pgDataSource:
    restoreFrom: ""
    restoreOpts: ""
  pgbadgerport: "10000"
  pgoimageprefix: registry.developers.crunchydata.com/crunchydata
  podAntiAffinity:
    default: preferred
    pgBackRest: preferred
    pgBouncer: preferred
  port: "5432"
  tolerations: []
  user: hippo
  userlabels:
    pgo-version: 4.7.0
